# Generated by Django 3.1.5 on 2021-02-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(max_length=200)),
                ('last_vote_date', models.DateTimeField(verbose_name='last vote date')),
            ],
        ),
    ]
